Add coveralls neo3.1
Financial-Times/alphaville-series-rw-neo4j pull request #9
Opened 2017-02-03 11:31 UTC by scott-ace-newton

Tests pass on circle ci :)
https://circleci.com/gh/Financial-Times/alphaville-series-rw-neo4j/35

2017-02-03 11:35 UTC, carlosroman approved these changes

2017-02-03 11:36 UTC, carlosroman requested changes
Sorry, just realised we are now using the official neo4j docker image.

2017-02-03 11:42 UTC, scott-ace-newton commented
Still passing
https://circleci.com/gh/Financial-Times/alphaville-series-rw-neo4j/36

2017-02-08 11:26 UTC, JuliaFernee approved these changes

2017-02-08 12:52 UTC, merged